/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdministracionUsuariosRouteImport } from './routes/_app.administracion.usuarios'
import { Route as AppAreasIndexRouteImport } from './routes/_app.areas.index'
import { Route as AppAreasNuevaRouteImport } from './routes/_app.areas.nueva'
import { Route as AppDiagnosticosIndexRouteImport } from './routes/_app.diagnosticos.index'
import { Route as AppDiagnosticosNuevoRouteImport } from './routes/_app.diagnosticos.nuevo'
import { Route as AppEmpleadosIndexRouteImport } from './routes/_app.empleados.index'
import { Route as AppEmpleadosNuevoRouteImport } from './routes/_app.empleados.nuevo'
import { Route as AppEquiposIndexRouteImport } from './routes/_app.equipos.index'
import { Route as AppEquiposNuevoRouteImport } from './routes/_app.equipos.nuevo'
import { Route as AppAreasAreaIdEditarRouteImport } from './routes/_app.areas.$areaId.editar'
import { Route as AppDiagnosticosDiagnosisIdIndexRouteImport } from './routes/_app.diagnosticos.$diagnosisId.index'
import { Route as AppDiagnosticosDiagnosisIdEditarRouteImport } from './routes/_app.diagnosticos.$diagnosisId.editar'
import { Route as AppDiagnosticosDiagnosisIdImprimirRouteImport } from './routes/_app.diagnosticos.$diagnosisId.imprimir'
import { Route as AppEmpleadosEmployeeIdIndexRouteImport } from './routes/_app.empleados.$employeeId.index'
import { Route as AppEmpleadosEmployeeIdEditarRouteImport } from './routes/_app.empleados.$employeeId.editar'
import { Route as AppEquiposEquipmentIdIndexRouteImport } from './routes/_app.equipos.$equipmentId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracionUsuariosRoute =
  AppAdministracionUsuariosRouteImport.update({
    id: '/administracion/usuarios',
    path: '/administracion/usuarios',
    getParentRoute: () => AppRoute,
  } as any)
const AppAreasIndexRoute = AppAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => AppRoute,
} as any)
const AppAreasNuevaRoute = AppAreasNuevaRouteImport.update({
  id: '/areas/nueva',
  path: '/areas/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticosIndexRoute = AppDiagnosticosIndexRouteImport.update({
  id: '/diagnosticos/',
  path: '/diagnosticos/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticosNuevoRoute = AppDiagnosticosNuevoRouteImport.update({
  id: '/diagnosticos/nuevo',
  path: '/diagnosticos/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosIndexRoute = AppEmpleadosIndexRouteImport.update({
  id: '/empleados/',
  path: '/empleados/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosNuevoRoute = AppEmpleadosNuevoRouteImport.update({
  id: '/empleados/nuevo',
  path: '/empleados/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppEquiposIndexRoute = AppEquiposIndexRouteImport.update({
  id: '/equipos/',
  path: '/equipos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEquiposNuevoRoute = AppEquiposNuevoRouteImport.update({
  id: '/equipos/nuevo',
  path: '/equipos/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppAreasAreaIdEditarRoute = AppAreasAreaIdEditarRouteImport.update({
  id: '/areas/$areaId/editar',
  path: '/areas/$areaId/editar',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticosDiagnosisIdIndexRoute =
  AppDiagnosticosDiagnosisIdIndexRouteImport.update({
    id: '/diagnosticos/$diagnosisId/',
    path: '/diagnosticos/$diagnosisId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDiagnosticosDiagnosisIdEditarRoute =
  AppDiagnosticosDiagnosisIdEditarRouteImport.update({
    id: '/diagnosticos/$diagnosisId/editar',
    path: '/diagnosticos/$diagnosisId/editar',
    getParentRoute: () => AppRoute,
  } as any)
const AppDiagnosticosDiagnosisIdImprimirRoute =
  AppDiagnosticosDiagnosisIdImprimirRouteImport.update({
    id: '/diagnosticos/$diagnosisId/imprimir',
    path: '/diagnosticos/$diagnosisId/imprimir',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmpleadosEmployeeIdIndexRoute =
  AppEmpleadosEmployeeIdIndexRouteImport.update({
    id: '/empleados/$employeeId/',
    path: '/empleados/$employeeId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmpleadosEmployeeIdEditarRoute =
  AppEmpleadosEmployeeIdEditarRouteImport.update({
    id: '/empleados/$employeeId/editar',
    path: '/empleados/$employeeId/editar',
    getParentRoute: () => AppRoute,
  } as any)
const AppEquiposEquipmentIdIndexRoute =
  AppEquiposEquipmentIdIndexRouteImport.update({
    id: '/equipos/$equipmentId/',
    path: '/equipos/$equipmentId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/administracion/usuarios': typeof AppAdministracionUsuariosRoute
  '/areas/nueva': typeof AppAreasNuevaRoute
  '/diagnosticos/nuevo': typeof AppDiagnosticosNuevoRoute
  '/empleados/nuevo': typeof AppEmpleadosNuevoRoute
  '/equipos/nuevo': typeof AppEquiposNuevoRoute
  '/areas/': typeof AppAreasIndexRoute
  '/diagnosticos/': typeof AppDiagnosticosIndexRoute
  '/empleados/': typeof AppEmpleadosIndexRoute
  '/equipos/': typeof AppEquiposIndexRoute
  '/areas/$areaId/editar': typeof AppAreasAreaIdEditarRoute
  '/diagnosticos/$diagnosisId/editar': typeof AppDiagnosticosDiagnosisIdEditarRoute
  '/diagnosticos/$diagnosisId/imprimir': typeof AppDiagnosticosDiagnosisIdImprimirRoute
  '/empleados/$employeeId/editar': typeof AppEmpleadosEmployeeIdEditarRoute
  '/diagnosticos/$diagnosisId/': typeof AppDiagnosticosDiagnosisIdIndexRoute
  '/empleados/$employeeId/': typeof AppEmpleadosEmployeeIdIndexRoute
  '/equipos/$equipmentId/': typeof AppEquiposEquipmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/administracion/usuarios': typeof AppAdministracionUsuariosRoute
  '/areas/nueva': typeof AppAreasNuevaRoute
  '/diagnosticos/nuevo': typeof AppDiagnosticosNuevoRoute
  '/empleados/nuevo': typeof AppEmpleadosNuevoRoute
  '/equipos/nuevo': typeof AppEquiposNuevoRoute
  '/areas': typeof AppAreasIndexRoute
  '/diagnosticos': typeof AppDiagnosticosIndexRoute
  '/empleados': typeof AppEmpleadosIndexRoute
  '/equipos': typeof AppEquiposIndexRoute
  '/areas/$areaId/editar': typeof AppAreasAreaIdEditarRoute
  '/diagnosticos/$diagnosisId/editar': typeof AppDiagnosticosDiagnosisIdEditarRoute
  '/diagnosticos/$diagnosisId/imprimir': typeof AppDiagnosticosDiagnosisIdImprimirRoute
  '/empleados/$employeeId/editar': typeof AppEmpleadosEmployeeIdEditarRoute
  '/diagnosticos/$diagnosisId': typeof AppDiagnosticosDiagnosisIdIndexRoute
  '/empleados/$employeeId': typeof AppEmpleadosEmployeeIdIndexRoute
  '/equipos/$equipmentId': typeof AppEquiposEquipmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/administracion/usuarios': typeof AppAdministracionUsuariosRoute
  '/_app/areas/nueva': typeof AppAreasNuevaRoute
  '/_app/diagnosticos/nuevo': typeof AppDiagnosticosNuevoRoute
  '/_app/empleados/nuevo': typeof AppEmpleadosNuevoRoute
  '/_app/equipos/nuevo': typeof AppEquiposNuevoRoute
  '/_app/areas/': typeof AppAreasIndexRoute
  '/_app/diagnosticos/': typeof AppDiagnosticosIndexRoute
  '/_app/empleados/': typeof AppEmpleadosIndexRoute
  '/_app/equipos/': typeof AppEquiposIndexRoute
  '/_app/areas/$areaId/editar': typeof AppAreasAreaIdEditarRoute
  '/_app/diagnosticos/$diagnosisId/editar': typeof AppDiagnosticosDiagnosisIdEditarRoute
  '/_app/diagnosticos/$diagnosisId/imprimir': typeof AppDiagnosticosDiagnosisIdImprimirRoute
  '/_app/empleados/$employeeId/editar': typeof AppEmpleadosEmployeeIdEditarRoute
  '/_app/diagnosticos/$diagnosisId/': typeof AppDiagnosticosDiagnosisIdIndexRoute
  '/_app/empleados/$employeeId/': typeof AppEmpleadosEmployeeIdIndexRoute
  '/_app/equipos/$equipmentId/': typeof AppEquiposEquipmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/administracion/usuarios'
    | '/areas/nueva'
    | '/diagnosticos/nuevo'
    | '/empleados/nuevo'
    | '/equipos/nuevo'
    | '/areas/'
    | '/diagnosticos/'
    | '/empleados/'
    | '/equipos/'
    | '/areas/$areaId/editar'
    | '/diagnosticos/$diagnosisId/editar'
    | '/diagnosticos/$diagnosisId/imprimir'
    | '/empleados/$employeeId/editar'
    | '/diagnosticos/$diagnosisId/'
    | '/empleados/$employeeId/'
    | '/equipos/$equipmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/administracion/usuarios'
    | '/areas/nueva'
    | '/diagnosticos/nuevo'
    | '/empleados/nuevo'
    | '/equipos/nuevo'
    | '/areas'
    | '/diagnosticos'
    | '/empleados'
    | '/equipos'
    | '/areas/$areaId/editar'
    | '/diagnosticos/$diagnosisId/editar'
    | '/diagnosticos/$diagnosisId/imprimir'
    | '/empleados/$employeeId/editar'
    | '/diagnosticos/$diagnosisId'
    | '/empleados/$employeeId'
    | '/equipos/$equipmentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/administracion/usuarios'
    | '/_app/areas/nueva'
    | '/_app/diagnosticos/nuevo'
    | '/_app/empleados/nuevo'
    | '/_app/equipos/nuevo'
    | '/_app/areas/'
    | '/_app/diagnosticos/'
    | '/_app/empleados/'
    | '/_app/equipos/'
    | '/_app/areas/$areaId/editar'
    | '/_app/diagnosticos/$diagnosisId/editar'
    | '/_app/diagnosticos/$diagnosisId/imprimir'
    | '/_app/empleados/$employeeId/editar'
    | '/_app/diagnosticos/$diagnosisId/'
    | '/_app/empleados/$employeeId/'
    | '/_app/equipos/$equipmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administracion/usuarios': {
      id: '/_app/administracion/usuarios'
      path: '/administracion/usuarios'
      fullPath: '/administracion/usuarios'
      preLoaderRoute: typeof AppAdministracionUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/areas/': {
      id: '/_app/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AppAreasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/areas/nueva': {
      id: '/_app/areas/nueva'
      path: '/areas/nueva'
      fullPath: '/areas/nueva'
      preLoaderRoute: typeof AppAreasNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnosticos/': {
      id: '/_app/diagnosticos/'
      path: '/diagnosticos'
      fullPath: '/diagnosticos/'
      preLoaderRoute: typeof AppDiagnosticosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnosticos/nuevo': {
      id: '/_app/diagnosticos/nuevo'
      path: '/diagnosticos/nuevo'
      fullPath: '/diagnosticos/nuevo'
      preLoaderRoute: typeof AppDiagnosticosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleados/': {
      id: '/_app/empleados/'
      path: '/empleados'
      fullPath: '/empleados/'
      preLoaderRoute: typeof AppEmpleadosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleados/nuevo': {
      id: '/_app/empleados/nuevo'
      path: '/empleados/nuevo'
      fullPath: '/empleados/nuevo'
      preLoaderRoute: typeof AppEmpleadosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos/': {
      id: '/_app/equipos/'
      path: '/equipos'
      fullPath: '/equipos/'
      preLoaderRoute: typeof AppEquiposIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos/nuevo': {
      id: '/_app/equipos/nuevo'
      path: '/equipos/nuevo'
      fullPath: '/equipos/nuevo'
      preLoaderRoute: typeof AppEquiposNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/areas/$areaId/editar': {
      id: '/_app/areas/$areaId/editar'
      path: '/areas/$areaId/editar'
      fullPath: '/areas/$areaId/editar'
      preLoaderRoute: typeof AppAreasAreaIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnosticos/$diagnosisId/': {
      id: '/_app/diagnosticos/$diagnosisId/'
      path: '/diagnosticos/$diagnosisId'
      fullPath: '/diagnosticos/$diagnosisId/'
      preLoaderRoute: typeof AppDiagnosticosDiagnosisIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnosticos/$diagnosisId/editar': {
      id: '/_app/diagnosticos/$diagnosisId/editar'
      path: '/diagnosticos/$diagnosisId/editar'
      fullPath: '/diagnosticos/$diagnosisId/editar'
      preLoaderRoute: typeof AppDiagnosticosDiagnosisIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diagnosticos/$diagnosisId/imprimir': {
      id: '/_app/diagnosticos/$diagnosisId/imprimir'
      path: '/diagnosticos/$diagnosisId/imprimir'
      fullPath: '/diagnosticos/$diagnosisId/imprimir'
      preLoaderRoute: typeof AppDiagnosticosDiagnosisIdImprimirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleados/$employeeId/': {
      id: '/_app/empleados/$employeeId/'
      path: '/empleados/$employeeId'
      fullPath: '/empleados/$employeeId/'
      preLoaderRoute: typeof AppEmpleadosEmployeeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empleados/$employeeId/editar': {
      id: '/_app/empleados/$employeeId/editar'
      path: '/empleados/$employeeId/editar'
      fullPath: '/empleados/$employeeId/editar'
      preLoaderRoute: typeof AppEmpleadosEmployeeIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos/$equipmentId/': {
      id: '/_app/equipos/$equipmentId/'
      path: '/equipos/$equipmentId'
      fullPath: '/equipos/$equipmentId/'
      preLoaderRoute: typeof AppEquiposEquipmentIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdministracionUsuariosRoute: typeof AppAdministracionUsuariosRoute
  AppAreasNuevaRoute: typeof AppAreasNuevaRoute
  AppDiagnosticosNuevoRoute: typeof AppDiagnosticosNuevoRoute
  AppEmpleadosNuevoRoute: typeof AppEmpleadosNuevoRoute
  AppEquiposNuevoRoute: typeof AppEquiposNuevoRoute
  AppAreasIndexRoute: typeof AppAreasIndexRoute
  AppDiagnosticosIndexRoute: typeof AppDiagnosticosIndexRoute
  AppEmpleadosIndexRoute: typeof AppEmpleadosIndexRoute
  AppEquiposIndexRoute: typeof AppEquiposIndexRoute
  AppAreasAreaIdEditarRoute: typeof AppAreasAreaIdEditarRoute
  AppDiagnosticosDiagnosisIdEditarRoute: typeof AppDiagnosticosDiagnosisIdEditarRoute
  AppDiagnosticosDiagnosisIdImprimirRoute: typeof AppDiagnosticosDiagnosisIdImprimirRoute
  AppEmpleadosEmployeeIdEditarRoute: typeof AppEmpleadosEmployeeIdEditarRoute
  AppDiagnosticosDiagnosisIdIndexRoute: typeof AppDiagnosticosDiagnosisIdIndexRoute
  AppEmpleadosEmployeeIdIndexRoute: typeof AppEmpleadosEmployeeIdIndexRoute
  AppEquiposEquipmentIdIndexRoute: typeof AppEquiposEquipmentIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAdministracionUsuariosRoute: AppAdministracionUsuariosRoute,
  AppAreasNuevaRoute: AppAreasNuevaRoute,
  AppDiagnosticosNuevoRoute: AppDiagnosticosNuevoRoute,
  AppEmpleadosNuevoRoute: AppEmpleadosNuevoRoute,
  AppEquiposNuevoRoute: AppEquiposNuevoRoute,
  AppAreasIndexRoute: AppAreasIndexRoute,
  AppDiagnosticosIndexRoute: AppDiagnosticosIndexRoute,
  AppEmpleadosIndexRoute: AppEmpleadosIndexRoute,
  AppEquiposIndexRoute: AppEquiposIndexRoute,
  AppAreasAreaIdEditarRoute: AppAreasAreaIdEditarRoute,
  AppDiagnosticosDiagnosisIdEditarRoute: AppDiagnosticosDiagnosisIdEditarRoute,
  AppDiagnosticosDiagnosisIdImprimirRoute:
    AppDiagnosticosDiagnosisIdImprimirRoute,
  AppEmpleadosEmployeeIdEditarRoute: AppEmpleadosEmployeeIdEditarRoute,
  AppDiagnosticosDiagnosisIdIndexRoute: AppDiagnosticosDiagnosisIdIndexRoute,
  AppEmpleadosEmployeeIdIndexRoute: AppEmpleadosEmployeeIdIndexRoute,
  AppEquiposEquipmentIdIndexRoute: AppEquiposEquipmentIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
